# -*- coding: utf-8 -*-
"""Calculo estocastico 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aum5C3TJRSwUQq30iEtSTkDpLgztAKxl

29 de abril
"""

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, IntSlider, FloatSlider
from IPython.display import display

def donsker_visualization(num_steps, num_paths):
    plt.figure(figsize=(10, 6))
    plt.title(f'Aproximación al Movimiento Browniano (Teorema de Donsker)\nPasos: {num_steps}, Caminos: {num_paths}')
    plt.xlabel('Tiempo')
    plt.ylabel('Posición')
    plt.grid(True)

    # Simulate and plot multiple scaled random walks
    for _ in range(num_paths):
        # Generate random steps (+1 or -1)
        steps = np.random.choice([-1, 1], size=num_steps)

        # Compute the partial sums (the random walk itself)
        random_walk = np.cumsum(steps)

        # Scale the random walk according to Donsker's Theorem
        # S_n(t) = (1/sqrt(n)) * S_floor(nt)
        # Here, we plot S_k / sqrt(num_steps) against k/num_steps
        scaled_random_walk = random_walk / np.sqrt(num_steps)

        # Create time points for the scaled walk
        time_points = np.linspace(0, 1, num_steps)

        plt.plot(time_points, scaled_random_walk, alpha=0.6, linewidth=0.8)

    plt.show()

# Create interactive widgets
num_steps_slider = IntSlider(min=10, max=1000, step=10, value=100, description='Número de pasos:')
num_paths_slider = IntSlider(min=1, max=100, step=1, value=5, description='Número de caminos:')

# Display the interactive visualization
interact(donsker_visualization, num_steps=num_steps_slider, num_paths=num_paths_slider);